### ISSUE TITLE
Expanding resources for the RSP project 

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/somerville-operations#100]
As we now have multiple devs who will be running Kubernetes clusters under the RSP project, we'll need to expand the resources.
To start with, could we double the Number of Volumes, and total RAM available?

**Comment by GregBlow** [comment]
Double number of volumes = 60 -> 120
total RAM available = 384GB -> 768GB

**Comment by GregBlow** [comment]
quota changed in live config

**Comment by GregBlow** [comment]
quota changed in repository bound config

**Comment by GregBlow** [comment]
@astrodb @stvoutsin  I've provided the changes in quota detailed. Please reopen if you'd like to query the matter further.
