### ISSUE TITLE
Cannot boot lasair bootstrap

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/somerville-operations#101]
Lasair is broken. Cannot log in at all. 
lasair-ztf-bootstrap == 10.66.3.4 == 192.41.122.151
Tried soft reboot, still doing it after 15 minutes

**Comment by astrodb** [comment]
I can't log into the management node either. That indicates a major outage at the ACF.

**Comment by astrodb** [comment]
Systems are back online. Check Lasair, and let me know here if it's not working. If it is, just close the ticket.

**Comment by RoyWilliams** [comment]
Fixed now. Thanks Mark and Greg!
