### ISSUE TITLE
Magnum not working

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/somerville-operations#105]
Attempting to list clusters in Horizon fails.
Attempting to use the CLI gives the following:
```
$ openstack coe cluster list
Timed out waiting for a reply to message ID 084c9a82fbfa48a7a32d3f2a4a1963f8 (HTTP 500) (Request-ID: req-fc4a953a-e2bc-43a4-8ca2-f5c3dc9adc06)
```

**Comment by stvoutsin** [comment]
I can confirm that I'm also seeing the same issues

**Comment by GregBlow** [comment]
`openstack coe cluster list` also fails from the cluster admin node, as admin.

**Comment by GregBlow** [comment]
@gpfrancis when did this last work correctly, please?

**Comment by gpfrancis** [comment]
I think @stvoutsin used Magnum when setting up the test and development RSP so it must have been working then. Was that last week?

**Comment by GregBlow** [comment]
Hi 
[@G Francis](https://ifaedinburghs-ofn4738.slack.com/team/U01QY8Q3RAT)
 you should be able to list clusters now. There was a problem with rabbitmq, and I had to restart it.

**Comment by markgbeckett** [comment]
Anything we can do to the things that we monitor, so we spot it in future?
