### ISSUE TITLE
Verify OVN version is >= 22.09

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/somerville-operations#106]
Can we verify which version of OVN we're running, and if it is >=22.09?

Last time I spoke to Piotr:

> It seems we would need to upgrade to OVN 22.09 and bump up ovn-octavia-provider version to support healthchecks - I'll have a look into this in coming days.

Do we know if we're running version 22.09 of OVN, and if HTTP Healthchecks for the LoadBalancer are now available?

**Comment by GregBlow** [comment]
In config I am still seeing that 22.06 is selected as the version override, need to verify live.

**Comment by GregBlow** [comment]
@stvoutsin 

I believe currently we're running 22.06 (as suggested before) and the planned upgrade to Yoga should take this to 22.09 as per Grzegorz's message:

https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1686574605297199?thread_ts=1686310400.675709&cid=C01Q56Q78LT
```
[stack@sv-ctrl-0 ~]$ docker run f3a5d25d1b56 rpm -qa| grep ovn
ovn22.09-22.09.0-11.el8s.x86_64
ovn22.09-host-22.09.0-11.el8s.x86_64
```

**Comment by stvoutsin** [comment]
Ok thanks @GregBlow I'll close this issue then
