### ISSUE TITLE
Cannot mount CephFS on some nodes

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/somerville-operations#109]
2 fails with 2 different errors and one success ....

```
ubuntu@lasair-ztf-ingest-0:~$ sudo mount /mnt/cephfs/
mount error 110 = Connection timed out
------------
ubuntu@lasair-ztf-bootstrap:~$ sudo mount /mnt/cephfs/
mount error 16 = Device or resource busy
-------------
ubuntu@lasair-ztf-svc:~$ sudo mount /mnt/cephfs/
ubuntu@lasair-ztf-svc:~$ ls -l /mnt/cephfs/
total 0
drwxr-xr-x 13 ubuntu ubuntu 11 Jun 15 00:34 lasair
drwxr-xr-x  4 ubuntu ubuntu  2 Apr 18 07:40 roy
drwxrwxrwx  2 root   root    1 Mar 16 14:15 test```

**Comment by astrodb** [comment]
what's the /etc/fstab/ line for the mount look like?

**Comment by astrodb** [comment]
`mount error 16 = Device or resource busy` - implies it's already mounted. If it's not listing anything, but giving that error, you'll need to unmount/remount.

**Comment by RoyWilliams** [comment]
Ok the busy one is already mounted, so thats OK. 
Just leaves one more the ingest, that times out.
All three have the same `/etc/fstab`

```
ubuntu@lasair-ztf-ingest-0:~$ cat /etc/fstab 
LABEL=cloudimg-rootfs	/	 ext4	defaults	0 1
LABEL=UEFI	/boot/efi	vfat	umask=0077	0 1
10.19.4.16:6789,10.19.4.17:6789,10.19.4.18:6789:/volumes/_nogroup/35153636-18ff-4368-9f9d-c79bbd07fbe4/05336ac5-0370-4636-b2ea-08495eb3fe04 /mnt/cephfs ceph secretfile=/etc/ceph/ceph.secret,name=lasair-ztf,noauto 0 0```

**Comment by astrodb** [comment]
Odd, the lasair-ztf-ingest-0 instance is getting `No route to host` errors trying to connect to the Ceph servers. But the local routing table is identical to the other instances where the mounts are working.

**Comment by astrodb** [comment]
Issue was with vlans on the switch. It's fixed now, and cephfs is mounted on lasair-ztf-ingest-0
