### ISSUE TITLE
3 more ceph mounts please

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/somerville-operations#110]
Thank you Mark for fixing the Ceph on lasair-ztf-ingest-0, the alert ingestion has been happy all weekend. 

Ken is visiting tomorrow and we would like to work on the development clusters also, where three more Ceph mounts are not working. Please can somebody take a look? -- Thank you , Roy
```
lasair-lsst-dev-ingest-0 (10.1.1.213) -- timed out

lasair-lsst-dev-filter-0 (10.1.1.63) -- timed out

deploy-test-svc (10.66.0.14)
~$ sudo mount /mnt/cephfs
did not load config file, using default settings.
2023-06-18T15:48:13.833+0000 7fc382918dc0 -1 Errors while parsing config file!
2023-06-18T15:48:13.833+0000 7fc382918dc0 -1 can't open ceph.conf: (2) No such file or directory
unable to get monitor info from DNS SRV with service name: ceph-mon
2023-06-18T15:48:13.845+0000 7fc382918dc0 -1 failed for service _ceph-mon._tcp
2023-06-18T15:48:13.845+0000 7fc382918dc0 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.deploy-test.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory
```

**Comment by GregBlow** [comment]
This may be a consequence of an infrastructure failure at the ACF:

https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1687113905002399

**Comment by GregBlow** [comment]
perhaps not, after evaluation incident does not seem like it would have affected service. Just a coincidence in timing. 

lasair-lsst-dev-ingest-0 hosted on sv-hpe-0-6
lasair-lsst-dev-filter-0 hosted on sv-hpe-0-6

**Comment by GregBlow** [comment]
verifying that VLAN 3308 is set correctly for sv-hpe-0-6

**Comment by GregBlow** [comment]
deploy-test-svc on sv-hpe-0-7, hypervisor host also has correct VLANs set.

**Comment by GregBlow** [comment]
cephFS interfaces on all three hosts Active:UP

**Comment by astrodb** [comment]
@RoyWilliams Can you add my key to the ubuntu user on one of the nodes with a public IP (like lasair-lsst-dev-ingest-0) so I can login and take a look? 

My key gets rejected on all the lasair-lsst-dev-... nodes, and it looks like the keys from lasair-ztf-bootstrap don't work either (which is fine, and probably intended).

**Comment by RoyWilliams** [comment]
I added the key euclid-mark to the authorized_users for both of the bootstrap nodes
ubuntu@192.41.122.218 (deploy-test) and
ubuntu@192.41.122.57 (lasair-lsst-dev)
From there you can get to any of the others.

**Comment by astrodb** [comment]
Um. Not sure you were doing, but it mounts fine from lasair-lsst-dev-filter-0

`root@lasair-lsst-dev-filter-0:/home/ubuntu# mount /mnt/cephfs
root@lasair-lsst-dev-filter-0:/home/ubuntu# df -h
Filesystem                                                                                                                                   Size  Used Avail Use% Mounted on
udev                                                                                                                                         2.0G     0  2.0G   0% /dev
tmpfs                                                                                                                                        394M  1.1M  393M   1% /run
/dev/sda1                                                                                                                                     25G  3.9G   21G  17% /
tmpfs                                                                                                                                        2.0G     0  2.0G   0% /dev/shm
tmpfs                                                                                                                                        5.0M     0  5.0M   0% /run/lock
tmpfs                                                                                                                                        2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/loop1                                                                                                                                    64M   64M     0 100% /snap/core20/1891
/dev/loop0                                                                                                                                    64M   64M     0 100% /snap/core20/1879
/dev/loop2                                                                                                                                    92M   92M     0 100% /snap/lxd/23991
/dev/loop3                                                                                                                                    92M   92M     0 100% /snap/lxd/24061
/dev/loop5                                                                                                                                    54M   54M     0 100% /snap/snapd/19122
/dev/loop4                                                                                                                                    54M   54M     0 100% /snap/snapd/19361
/dev/sda15                                                                                                                                   105M  5.2M  100M   5% /boot/efi
tmpfs                                                                                                                                        394M     0  394M   0% /run/user/1000
10.19.4.16:6789,10.19.4.17:6789,10.19.4.18:6789:/volumes/_nogroup/c5cd0ade-d935-40d4-bb0f-737f49657867/47822fc5-97c9-48ed-9450-3116659b69ab 1000G   66G  935G   7% /mnt/cephfs
`

**Comment by astrodb** [comment]
And none of the necessary setup has been done on lasair-lsst-dev-ingest-0. There is no line in the mount file, no ceph secret file, and the /mnt/cephfs directory has not been created. I'm leaving all that to you.

**Comment by astrodb** [comment]
@RoyWilliams Is this still a problem, or can I close the issue?
