### ISSUE TITLE
Increase in share space

### ISSUE THREAD

**Issue by aibsen** [lsst-uk/somerville-operations#113]
In order to make the HSC-VISTA dataset available via the notebook aspect in the RSP we need ~25 TBs. While there is enough space for a Volume, we currently have only ~4TB of available space for Shares. It would be better to have this dataset in a Share so it can be accessed by several Instances (like rsp-nfs and rsp-test-nfs) at the same time.

**Comment by GregBlow** [comment]
Good morning,

I've doubled the space quota available to RSP. 

Please test and confirm, closing the issue if this solves the matter. Thank you. 

Regards,

Greg

**Comment by aibsen** [comment]
Hi Greg, 

Yes, the space quota has indeed doubled. However, that leaves is with ~8TB, but we need ~25TB. Can it be increased further?

**Comment by GregBlow** [comment]
Ah, apologies. Didn't parse the request correctly. Yes, I've increased the quota to 48TB.

**Comment by aibsen** [comment]
Thanks, I confirm the issue is solved :)
