### ISSUE TITLE
Increase VCPU on RSP to 240

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/somerville-operations#114]
Currently using 121 of 152. Need to create one more 5 node cluster which will use aprox. 40 VCPU, which is not currently possible with the existing allocation

**Comment by GregBlow** [comment]
Hello Stelios, we'll look at getting this applied this afternoon.

**Comment by DP-B21** [comment]
Hi Stelios, this is done. Please close this issue if you are satisfied.

**Comment by stvoutsin** [comment]
Thanks, looks good
