### ISSUE TITLE
Increase floating IPs on RSP by 20

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/somerville-operations#115]
Currently using 30 out of 36. Need to increase that to be able to create two more clusters, assuming additional IPs are available.

**Comment by stvoutsin** [comment]
Note that I've requested 20, but we don't necessarily need that many now if they are needed elsewhere

**Comment by DP-B21** [comment]
Hi, this also is completed although I forgot to give you an update here XD

**Comment by stvoutsin** [comment]
Great thanks, closing this issue then
