### ISSUE TITLE
Upgrade OS on management container

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#117]
The management container is running Ubuntu 18 LTS, which is now off standard support (as of June). It would be a good idea to upgrade it (or replace it) with Ubuntu 22 to stay up-to-date.

**Comment by GregBlow** [comment]
need to:

- timetable (will look to do this afternoon, unless there is a conflict)
- snapshot
- update

**Comment by GregBlow** [comment]
Executing this afternoon.

process:

https://www.wiki.ed.ac.uk/display/EHST/20230823-+somerville-mgmt+OS+upgrade

**Comment by GregBlow** [comment]
someville-mgmt upgraded to ubuntu 22 (jammy). Leaving issue and snapshot in place for 2 weeks to allow for rollback if unforeseen consequences.

```
root@somerville-mgmt:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Comment by GregBlow** [comment]
snapshot deleted. issue closed.
