### ISSUE TITLE
Create qserv-czar-test flavour at 4* size of qserv-czar-dev

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#120]
Testing of ingest process suggests RAM of development flavour is insufficient for ingest process to complete without incident. Suggest rebuilding cluster with expanded flavours for czar and possibly also utility nodes to verify. In terms of labour effort probably best to presume both flavours need expanding, then test whether we can get away with just a chunkier czar after verifying better functioning.

**Comment by markgbeckett** [comment]
If confirmed to be lack of memory, is there anything we can do to improve the error reporting from Qserv for situations when it runs out of memory?

**Comment by GregBlow** [comment]
I don't think so, at least not economically. At this point in time a strong familiarity with Qserv/Kubernetes has to be assumed.

I think instead what would be more useful is a more robust set of troubleshooting instructions here, or thereabouts:

https://qserv.lsst.io/admin/qserv-ingest/run.html

based on a set of case studies of malfunctioning clusters, like an FAQ. (e.g. Q: Running ingest causes a single ingest pod of 2 containers to run for two minutes before erroring out without explanation. A: Turn on verbose logging here (provide instructions) and check log here (provide example command) ) 

Mike has some instructions here:

https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3259957261/Qserv+testing

that have been useful, but don't seem to be sufficient to reset the cluster to a freshly provisioned state for repeat testing. 

Being able to do that would also be helpful in reducing the time to iterate, as I am presently tearing down and reprovisioning the cluster because I cannot clean down an existing one to reproduce the behaviour of a freshly provisioned cluster.

**Comment by GregBlow** [comment]
(in the example given I think the reason is that the dataserver isn't running, although thus far I've only managed to launch it through the e2e integration test, which seems wrong. )

**Comment by GregBlow** [comment]
done
