### ISSUE TITLE
Are floating IP addresses public ?

### ISSUE THREAD

**Issue by Zarquan** [lsst-uk/somerville-operations#122]
Are the floating IP addresses intended to be public ?

The [Networking wiki page](https://github.com/lsst-uk/somerville-operations/wiki/Networking#floating-ips) seems to suggest that a floating IP address added to a VM should be accessible from the public internets.

As a test I have a  VM with a floating IP, on an internal network with a router linking it to the external network. If I have the Edinburgh VPN active, I can login to the VM using `ssh`. Without the Edinburgh VPN I get a connection timeout.

```
ssh -v fedora@192.41.122.29 'date; hostname'
....
....
debug1: Connecting to 192.41.122.29 [192.41.122.29] port 22.
debug1: connect to address 192.41.122.29 port 22: Connection timed out
ssh: connect to host 192.41.122.29 port 22: Connection timed out

```

**Comment by GregBlow** [comment]
Hello,

No, they're restricted to a whitelist of address ranges, generally under the ownership of a known institution. I think 'publically addressable' might want to be on the 'external network'.

Are there some ports/addresses you'd like exposed to the wider internet? 

Regards,

Greg

**Comment by Zarquan** [comment]
>  ... they're restricted to a whitelist of address ranges, 

Your documentation doesn't say that

https://github.com/lsst-uk/somerville-operations/wiki/Networking#floating-ips
> Each project will be given 3 publicly addressable IPs  ...projects should use them for ... public services (web servers, etc). 

So how do I make a service public ?

**Comment by Zarquan** [comment]
Could you add `90.155.51.57/32` and `81.187.152.17/28` to the white list please.

**Comment by astrodb** [comment]
@GregBlow have those addresses been added to the firewall?

**Comment by GregBlow** [comment]
I'm afraid not yet, no. I've made the request.

**Comment by Zarquan** [comment]
ping ?
Any news on adding these addresses to the firewall

**Comment by GregBlow** [comment]
Apologies, I am chasing putting a hole in the firewall now.

**Comment by GregBlow** [comment]
Hello Dave,

These look like personal IP addresses. Our network team has asked if there a reason please why the UoE VPN can't be used? Thank you.

Regards,

Greg

**Comment by Zarquan** [comment]
1) Define _'personal'_.
2) I don't use the UoE VPN because the UoE VPN allocates addresses on the 10.0.0.0 network, which is fine if all you have is a laptop. I have multiple machines connected to a local 10.0.0.0 network, so using the UoE VPN causes all kinds of problems including multiple default routes and re-routing of internal DNS requests. The UoE VPN causes similar problems when visiting other institutes that also have a 10.0.0.0 network. The UoE VPN works for a simple laptop, it does not play nice with more complex configurations.

3) Is there a white list of approved organisations that your network team consider suitable? If so, please publish details of the approval process so that I can apply.

4) Your documentation says :
> Each project will be given 3 publicly addressable IPs ... projects should use them for ... public services (web servers, etc).

It says _"publicly addressable IPs"_, it does not mention a restricted white list of approved sites only.

5) Eventually our project will need to provides _"public services (web servers, etc)"_ to the public. I will leave it for someone else to sort out the politics on that. Getting my address range added to the approved list is a work around that lets me get on with my job, developing the software.

**Comment by Zarquan** [comment]
I re-read the documentation, and although the first paragraph refers to _"public services (web servers, etc)"_ without mentioning any restrictions, the second paragraph does indeed mention a _"firewall which restricts access to some ports to known addresses"_, specifically calling out SSH as one of the ports that are restricted.

Does that mean that the ports for HTTP and HTTPS are open and only SSH is restricted ? In which case, please can I get my address range added to the approved list for SSH.

**Comment by GregBlow** [comment]
Hello,

1) personal in this case is derived from seeing that the /28 block of addresses were identified as an Andrews and Arnold set:

https://ipinfo.io/AS20712/81.187.0.0/16-81.187.152.0/23

not positively identified with an institution; generic insofar as they are only identied with an ISP. 

The single address was not identified.

If you can provide information about what these are it would be useful.

2-5) I think these are service questions which may need to have @astrodb comment, although the answer to 2) is a useful rationale as to why VPN is inadequate to the task, which I will also pass on to the EPCC network team. 

Apologies for the difficulty.

Regards,

Greg

**Comment by Zarquan** [comment]
Both the /28 block and the single address are allocated to me by Andrews and Arnold and routed to my residential FTP line. Along with an IPv6 block, 2001:8b0:be72::/48, of which 2001:8b0:be72:d4eb::/64 is also routed to my network.

**Comment by Zarquan** [comment]
Just to be technically accurate, my /28 block is https://ipinfo.io/AS20712/81.187.0.0/16-81.187.152.17/23

**Comment by astrodb** [comment]
@GregBlow Is there a technical reason we can't approve these ranges? These are already present in other servers at ROE, and we haven't had an issue.

**Comment by GregBlow** [comment]
hello, no there is no technical reason. The concern was just about the anonymity of the addresses.

**Comment by astrodb** [comment]
No longer needed.
