### ISSUE TITLE
somerville.ed.ac.uk server error.

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#126]
somerville.ed.ac.uk is presently returning a server error. No HTTP error code:

![image](https://github.com/lsst-uk/somerville-operations/assets/2021333/112fc0fc-a4b1-4acb-9639-2a08ad28cc94)

**Comment by GregBlow** [comment]
Appears to be related to maintenance. StackHPC report web interface is working for them. Reported Separately by Amanda Ibsen.

**Comment by DP-B21** [comment]
I also see this issue, I am connected to the university's wireless connection, with Wireguard on

**Comment by GregBlow** [comment]
Seem to have access again to somerville.ed.ac.uk.

**Comment by DP-B21** [comment]
I can also access it as of now

**Comment by GregBlow** [comment]
Piotr recreated horizon containers to resolve.
