### ISSUE TITLE
CephSSD filesystem at capacity, volumes not deleteable.

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#131]
Issue reported by @gpfrancis . Ceph SSD file system at effective capactiy. Volumes not possible to delete even with attachment deletion and forced state changes.

**Comment by GregBlow** [comment]
Have atempted to delete the Qserv October 23 cluster to create sufficient space. However volumes become stuck in `detaching` state. Force deleting the attachment puts the volumes into `error_deleting state`. Adverted to Piotr Parczewski at StackHPC, who `ceph osd set-full-ratio .96` to set ceph cluster to non-readonly state. Provided list of volumes to delete.

**Comment by GregBlow** [comment]
`cinder attachment-delete 88c83213-dfee-46be-8100-086f9d57eeff`
`cinder delete cf8762a4-5725-4b2d-8e9c-006e06785a7c`
Are commands used to delete the attachment and volume

`cinder reset-state c4a96924-ea12-4453-bb9f-7a339373632f --state error`

Resets the db status of the volume to make it deleteable.

**Comment by astrodb** [comment]
Issue was finally solved by setting: `ceph osd set-full-ratio .96`
And then deleting enough volumes to clear the space.

**Comment by astrodb** [comment]
Next step is to look at applying system quotas on the Ceph pools as descibed here: https://docs.ceph.com/en/quincy/rados/operations/pools/#setting-pool-quotas
