### ISSUE TITLE
Review of Somerville Service Strategy prior to RSAP for 2025

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/somerville-operations#136]
Service Strategy document at https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3263561729/Somerville+Service+Strategy
requires a review in August 2024 prior to the IRIS RSAP for 2025

**Comment by tms-epcc** [comment]
Note : Deadline for RSAP submission is 05/NOV/24

**Comment by astrodb** [comment]
No changes made, no issues with the strategy raised by projects.
