### ISSUE TITLE
Write up SOP on Somerville ACF wiki for remote accessing iLO

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#143]
Write up a full SOP on accessing the iLO interfaces remotely. Include the ssh commands/config needed (as a double hop through the mgmt container to the admin node), how to get the access credentials, etc.

**Comment by GregBlow** [comment]
Started here:

https://www.wiki.ed.ac.uk/pages/viewpage.action?pageId=614009093

**Comment by astrodb** [comment]
Looks good, but it should include the steps for obtaining the login credentials. We need this to be fully usable for someone from the ACF who's not logged in before.

**Comment by GregBlow** [comment]
I've added further sections on where credentials are kept (ACF bitwarden) and how to reach sv-admin-0. 

Will restructure the SOP to be a more general 'how to access Somerville mgmt & sv-admin-0 & cluster nodes & bmcs'.

**Comment by GregBlow** [comment]
rewriting done. https://www.wiki.ed.ac.uk/pages/viewpage.action?pageId=614009093
