### ISSUE TITLE
VM flavors for Gaia DMP

### ISSUE THREAD

**Issue by Zarquan** [lsst-uk/somerville-operations#145]
In order to create a full Zeppelin/Spark deployment we need to create some new VM flavors to match those used on the Cambridge Arcus system.

```
  {
    "ID": "....",
    "Name": "gaia.vm.2vcpu",
    "RAM": 3072,
    "Disk": 14,
    "Ephemeral": 0,
    "VCPUs": 2
  },
  {
    "ID": "....",
    "Name": "gaia.vm.4vcpu",
    "RAM": 6144,
    "Disk": 22,
    "Ephemeral": 0,
    "VCPUs": 4
  },
  {
    "ID": "....",
    "Name": "gaia.vm.26vcpu",
    "RAM": 44032,
    "Disk": 20,
    "Ephemeral": 180,
    "VCPUs": 26
  }
```

**Comment by GregBlow** [comment]
Good morning,

The university is presently having problems with it's source control platform, which we use for deploying flavors. I can have these flavors created directly if it's urgent, otherwise expected time of resolution of the blocking issue is tomorrow.

**Comment by Zarquan** [comment]
No problem. Not urgent. Thanks.

**Comment by Zarquan** [comment]
@GregBlow is the source control available now ? It would be good to be able to use the new flavors this weekend.

**Comment by GregBlow** [comment]
@DP-B21 has coded the new flavours earlier today, however it appears that there is presently an issue running the ansible playbooks that apply them out to openstack. I've popped a query in slack to StackHPC to see if this is a straightforward fix, but regardless I'll see to getting these out on Monday.

**Comment by GregBlow** [comment]
Good morning,

The elegant way of implementing this is still broken, so I've gone ahead and implemented expediently. Could you please test and verify, @Zarquan . Thank you.

**Comment by Zarquan** [comment]
Ne wflavors tested :+1:
