### ISSUE TITLE
Running Tempest

### ISSUE THREAD

**Issue by Alex-Welsh** [lsst-uk/somerville-operations#148]
Notes for running tempest:

1. Under `src/kayobe-config` run `git submodule init && git submodule update`
2. Config goes under `kayobe-config/.automation.conf/config.sh` and `kayobe-config/.automation.conf/tempest/tempest-somerville.overrides.conf`
3. The defaults should run the shorter refstack test list (~330 tests) but there is longer tempest-full list (>1000 tests). This can be chosen in `config.sh`
4. Messy workaround: These lines must be added to `kayobe-config/.automation/ansible/kayobe-automation-run-tempest.yml` in the `Run tempest` play, below the line `-v "{{ results_path_remote.path }}:/home/rally/artifacts"`:

```
          --name tempest
          --env http_proxy=http://172.24.53.250:3128
          --env https_proxy=http://172.24.53.250:3128
          --env HTTP_PROXY=http://172.24.53.250:3128
          --env HTTPS_PROXY=http://172.24.53.250:3128
          --env no_proxy=localhost,127.0.0.1,10.19.2.41,10.19.3.200
```

5. Export the automation SSH key: `export KAYOBE_AUTOMATION_SSH_PRIVATE_KEY=$(cat ~/.ssh/id_rsa)`
6. Ensure a kayobe-config/tempest-artifacts directory exists: `mkdir tempest-artifacts`
8. Run the tests (from the kayobe-config directory): `time sudo -E docker run -it --rm --name kayobecontainer --env TEMPEST_OPENRC="$(< $KAYOBE_CONFIG_PATH/../kolla/admin-openrc.sh)" --network host -v $(pwd):/stack/kayobe-automation-env/src/kayobe-config -v $(pwd)/tempest-artifacts:/stack/tempest-artifacts -e KAYOBE_ENVIRONMENT -e KAYOBE_VAULT_PASSWORD -e KAYOBE_AUTOMATION_SSH_PRIVATE_KEY kayobe:latest /stack/kayobe-automation-env/src/kayobe-config/.automation/pipeline/tempest.sh -e ansible_user=stack`
9. This will create a kayobe automation container which itself will spawn a tempest container after about a minute. You can follow the progress with `docker logs -f tempest` in another terminal. In total it should take around 15 minutes for a refstack test run.
11. Once it is finished, it will dump the results into the kayobe-config/tempest-artifacts directory:
  a. `Failed-tests` is a simple list of tests that failed
  b. `Rally-verify-report.html` is a nice page that, if you scp it back to your local machine, can be opened with a web browser to see results.
  c. `Rally-verify-report.json` outputs test results in json format
The remainder are logs for debugging

Once set up, tempest can be re-run by simply running the main `docker run` command. Be aware that it will overwrite the tempest-artifacts directory so copy out any previous results you wish to keep

**Comment by GregBlow** [comment]
Have run through and looks to be working, will transcribe to our documentation. Thank you.
