### ISSUE TITLE
New project request

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/somerville-operations#150]
Hi, please could you create a new temporary project that we can use to experiment with using the GAIA K8s deployment code as a potential backup plan to replace Magnum for RSP? Expected usage would be up to ~10 instances with a mixture of tiny and medium.

**Comment by GregBlow** [comment]
I've created `RSP-test` and assigned myself, Stelios, and yourself to the member list. It's not in config as it's only meant to be ephemeral. Set a quota to accomodate 10*medium instances. We may need to look at configuring the project's network. Is this project ok to be completely isolated from RSP proper?

**Comment by gpfrancis** [comment]
Yes, full isolation is probably for the best anway.

**Comment by GregBlow** [comment]
I've added an rsp-test network, subnet, and router.

**Comment by GregBlow** [comment]
closing issue. If any amendments are required, please reopen.
