### ISSUE TITLE
Add Stelios to Gaia project

### ISSUE THREAD

**Issue by Zarquan** [lsst-uk/somerville-operations#152]
Can you add Stelios <stv [at] roe.ac.uk> to the Gaia-Jade Openstack project.

**Comment by GregBlow** [comment]
Good afternoon, sorry I haven't responded to this. This request looks to be redundant, Stelios already has roles on the Somerville-Gaia-Jade project. @stvoutsin please verify?

**Comment by astrodb** [comment]
@stvoutsin IRIS IAM seems to think you're in ther group. Can you verify?
