### ISSUE TITLE
Add Malcolm Illingworth to the Gaia DMp project

### ISSUE THREAD

**Issue by Zarquan** [lsst-uk/somerville-operations#154]
Malcolm Illingworth <m.illingworth [at] epcc.ed.ac.uk> is joining the Gaia Data Mining platform team.

Could you add Malcolm to the Gaia-Jade Openstack project, add him to the <iris-somerville-users-request [at] mlist.is.ed.ac.uk> mailing list and the IfA Edinburgh (Somerville) Slack workspace.

Thanks.

**Comment by Zarquan** [comment]
Also - could you remove my accounts at the end of March.

**Comment by GregBlow** [comment]
- [x] M.Illingworth signed up and approved for esa/gaia 
- [x] M.Illingworth added to iris-somerville-users mailing list
- [ ] @Zarquan removed from mailing list and Somerville //31/03/2024

**Comment by Zarquan** [comment]
@GregBlow  Could you hold off on deleting my accounts. It will be useful for me to be able to login to the platform to help Malcolm after I have moved to Manchester.

**Comment by Zarquan** [comment]
Just checking, do we need to add https://github.com/millingw so that he can create issues in this project ?

**Comment by GregBlow** [comment]
This is a public repository, it doesn't require individuals to be granted permission to post.
