### ISSUE TITLE
Increase RAM allocation for RSP project

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/somerville-operations#157]
Currently Used 988GB of 1TB
If the resources are available could we increase to 1.5 TB?

**Comment by GregBlow** [comment]
Change seems reasonable given current system resource uses. I've made change in config and am applying now.

**Comment by GregBlow** [comment]
That looks to have applied successfully. Please test and verify.

**Comment by GregBlow** [comment]
closing without verification
