### ISSUE TITLE
Configure somerville-perfsonar to provide useful data

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#164]
- troubleshoot basic tests
- formulate meaningful tests to demonstrate production level functioning

**Comment by GregBlow** [comment]
potentially useful:

https://youtu.be/9OyJsQB59Yg?si=da1GdleIqCBs-TY7&t=500

**Comment by GregBlow** [comment]
Working on dedicated hardware based solution (hostname: perfsonar01) first to eliminate virtual networking eccentricities as a source of interference.

**Comment by GregBlow** [comment]
CR1 hardware node up at perfsonar01.epcc.ed.ac.uk, configured to talk to Somerville hosted node with data looking good. Also configured to talk to JISC nodes. 

<img width="1507" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRPQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be9c2581cce6b136cb423539a741cfa96d411018/image.png" alt="image.png" />

node up at somerville.perfsonar.ed.ac.uk 

<img width="1503" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMElPQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff8749837a6027e77f8572616a8df87b99cfc50c/image.png" alt="image.png" />

Discussions ongoing with Rubin later today to help determine scope and useful targets, and JASMIN on a separate channel.

**Comment by GregBlow** [comment]
To talk to Peter Love re connecting up Lancaster & RAL

**Comment by tms-epcc** [comment]
Done
