### ISSUE TITLE
Create project for Adler

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#169]
Create a project for the Adler team:

- [ ] Create project with resource quotas of: 30 cores, 100GB RAM, 2TB volumes
- [ ] Get list of IAM accounts which need access
- [ ] Add list of accounts to project as owners
- [ ] Contact Addler team (Meg Schwamb m.schwamb@qub.ac.uk) with instructions for login, pointers to documentation

**Comment by astrodb** [comment]
Issue moved to #170

**Comment by GregBlow** [comment]
closing as all additional information transcribed to #170
