### ISSUE TITLE
New project - Adler

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#170]
New project for WP 3.6 Adler solar system transient classification.  

> We are at the stage where we want to start working on our component that will be integrated in Lasair, the LSST UK broker.  We would like to get some resources on Somerville to be able start that development. Would you be able to start a project for us?
> 
> The duration would be for 3 years.  We would like 20 cores and 80GB of memory and 1 Tb of disk space.

- [x] Write openstack resources definitions
  - [x] project
  - [x] project quota
  - [x] network 
  - [x] default security group
- [x] Deploy openstack resources
- [x] Manually create openstack resources
  - [x] v.router 
- [x] Create iris IAM resources
- [x] enroll first (admin) users to iris IAM group
- [x] connect iris IAM group to openstack project
- [x] Get list of IAM accounts which need access
- [x] Add list of accounts to project as owners
- [x] Contact Addler team (Meg Schwamb m.schwamb@qub.ac.uk) with instructions for login, pointers to documentation

**Comment by astrodb** [comment]
I've emailed the user requesting a list of IAM accounts to add to the project. Will post here when ready.

**Comment by GregBlow** [comment]
revised starting quota:

- 30 cores
- 100GB RAM, 
- 2TB volumes

**Comment by GregBlow** [comment]
@DP-B21 please create the openstack resource definitions on the gitlab repository. Once that's done we'll review and deploy.

**Comment by GregBlow** [comment]
https://git.ecdf.ed.ac.uk/lsstuk-somerville/openstack-config/-/merge_requests/104

**Comment by GregBlow** [comment]
@DP-B21 definitions look good, these can be deployed now as per SOP. Thank you.

**Comment by GregBlow** [comment]
deployment of network blocked (possibly) by sv-admin-0 being on a different branch. Holding off on creating network manually to avoid creating redundant (possibly conflicting) networks.

**Comment by GregBlow** [comment]
Not had a response from iris-iam yet. Will create local user accounts tomorrow.

**Comment by GregBlow** [comment]
All tasks should now be complete. Leaving open until end of week to confirm all present and correct as per users expectations.
