### ISSUE TITLE
Clean up instances and volumes in 'test' project

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#177]
It looks like there is a lot of testing remnants, both instances and volumes, in the 'test' project which should be cleaned up. Greg will look at the instances and clear those no longer needed. Mark is looking into clearing out the large number of unused volumes.

**Comment by astrodb** [comment]
I've cleaned out ~8 volumes in state "Reserved" left over from the CephSSD over-filling episode. Delete from Horizon failed, but using the CLI with the `--force` parameter worked.

**Comment by astrodb** [comment]
I cleaned out ~200 volumes which all appeared to be leftover from test instance OS disks no longer in use.

There are 3 which won't delete due to having snapshots:
https://somerville.ed.ac.uk/project/volumes/32919853-eaf4-44fd-8a3c-99d6f41e8b26/ 
https://somerville.ed.ac.uk/project/volumes/0295b9cd-22fa-4220-8299-98d2bfb2cb46/ 
https://somerville.ed.ac.uk/project/volumes/d15233e1-6be5-4647-bf9b-67e520508ed4/

@DP-B21 those look like yours, are they still in use? No problem if so, but if they aren't of any use anymore it would be good to delete the snapshots and the volumes.

**Comment by DP-B21** [comment]
hey I will check them a clean them. thanks for the heads up

**Comment by DP-B21** [comment]
I have deleted the VMs i am responsible for and some of their respective volumes. Thanks
