### ISSUE TITLE
SSH Version checking for hosted instances

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#178]
Write a script which generates a report of all instances with public IPs listening on SSH, along with their SSH protocol and version numbers. This will be used going forward to check CVE patching of SSH on Somerville.

Name the script so we know what it is, and check it into here for future use/reference: https://git.ecdf.ed.ac.uk/lsstuk-somerville/somerville-admin-tools-and-scripts

**Comment by astrodb** [comment]
Put the script in here: https://git.ecdf.ed.ac.uk/lsstuk-somerville/somerville-admin-tools-and-scripts/-/tree/main/Security_Scripts_and_Scans?ref_type=heads

**Comment by DP-B21** [comment]
Hi, I have uploaded the script onto the repo, could you please check the permissions so i can update this script via the CLI? thanks

**Comment by GregBlow** [comment]
The main branch of the repo is protected, which is a good practice. To update via the CLI I would recommend committing to a different branch and merging cumulative changes to the main branch when you reach a milestone.

**Comment by GregBlow** [comment]
looks like you're only a developer role, which is below the maintainer level needed to merge to protected branches. That should be fixed.

**Comment by GregBlow** [comment]
I've done that now.

**Comment by astrodb** [comment]
I've given a test run to the version here: https://git.ecdf.ed.ac.uk/lsstuk-somerville/somerville-admin-tools-and-scripts/-/blob/main/Security_Scripts_and_Scans/ssh_check.sh?ref_type=heads

Works as requested! Just a couple notes/suggestions:

1. Don't assume/use locations in `/etc` for this sort of script. `/etc` is a location for OS and service configuration files. This sort of script should be coded standalone, and assume/use relative paths for any output files. Given the simplicity of the script/test. outputting to the same directly as the location of the script file makes sense.
2. The script creates a file in `/tmp` but never uses it. Is this a placeholder for a future modificiation?
3. For improving the report readability, it might be worth not outputting anything for addresses where SSH isn't detected.

**Comment by DP-B21** [comment]
Thats great! answering your questions:

1. yes I will work on making the files to revolve around the script's directory rather than using `/etc`
2.  `/tmp` is for a future placeholder indeed, thank you for pointing this out and I will create a merge request promptly
3. I have intentions to create a file of the last known ssh versions/state and a file which points out the differences from the last check e.g: `IP: 192.41.122.xxx has changed ssh version | IP: 192.41.122.xxx is online/offline now`

**Comment by DP-B21** [comment]
Script has been updated with removed temporary file creation

**Comment by DP-B21** [comment]
Hi @astrodb here I have pushed and more updated version of the file. please let me know what you think of how it works for you. Thanks

**Comment by astrodb** [comment]
Looks good to me. Does everything it needs to, thanks.
