### ISSUE TITLE
projects deployment playbook not working

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#181]
Attempting to run `(openstack-config) [stack@sv-admin-0 openstack-config]$  tools/somerville-config -p ansible/somerville-project.yml` results in an error on (openstack-config) [stack@sv-admin-0 openstack-config]$  tools/somerville-config -p ansible/somerville-project.yml. Replicating command outside of ansible indicates function is not supported. (Attempts to use admin interface for keystone, which doesn't look to exist).

**Comment by GregBlow** [comment]
> reg Blow
>   3 hours ago
> trying to apply quota changes using ansible and getting:
> TASK [stackhpc.openstack.os_projects : List OpenStack domains] **************************************************************************************************************************************************
> fatal: [localhost]: FAILED! => {"changed": false, "cmd": ". /home/stack/kayobe/src/openstack-config/ansible/somerville-config-venv/bin/activate && openstack  --os-project-domain-id=''  --os-user-domain-id=''  --os-project-domain-name='Default'  --os-user-domain-name='Default'  --os-project-id=''  --os-project-name='admin'  --os-username='admin'  --os-password='<REDACTED>'  --os-auth-url='http://10.19.3.200:5000'   --os-cacert=''   --os-interface=admin domain list -f json -c Name -c ID\n", "delta": "0:00:01.439531", "end": "2024-07-19 13:06:33.656971", "msg": "non-zero return code", "rc": 1, "start": "2024-07-19 13:06:32.217440", "stderr": "admin endpoint for identity service in RegionOne region not found", "stderr_lines": ["admin endpoint for identity service in RegionOne region not found"], "stdout": "", "stdout_lines": []}
> (edited)
> 
> 
> 
> 
> 14 replies
> 
> 
> Mark Holliman
>   [3 hours ago](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1721394472796489)
> login credential file is out of date?
> 
> 
> Mark Holliman
>   3 hours ago
> check you're in the right project?
> 
> 
> Greg Blow
>   3 hours ago
> I don't know. admin endpoint for identity service in Regionone region not found doesn't sound like a credentials error.
> 
> 
> Mark Holliman
>   3 hours ago
> Google search shows a lot of things all related to misconfigured env settings, or the service being offline
> 
> 
> Mark Holliman
>   3 hours ago
> Just checked, and keystone is listening on 10.19.3.200:5000, visible from admin node
> 
> 
> Greg Blow
>   3 hours ago
> references the venv at /home/stack/kayobe/src/openstack-config/ansible/somerville-config-venv/bin/activate
> 
> 
> Greg Blow
>   3 hours ago
> git repo there has
> image.png
>  
> image.png
> 
> 
> 
> 
> Greg Blow
>   3 hours ago
> changing os-interface from admin to internal causes the failed command to return properly, rather than erroring out.
> 
> 
> Greg Blow
>   2 hours ago
>   --os-interface <interface>
>                         Select an interface type. Valid interface types:
>                         [admin, public, internal]. default=public, (Env:
>                         OS_INTERFACE)
> 
> 
> Greg Blow
>   2 hours ago
> (openstack-config) [stack@sv-admin-0 openstack-config]$ openstack endpoint list | grep keystone
> | 12a633c81bbd412692f80c4600cb3008 | RegionOne | keystone     | identity        | True    | public    | https://somerville.ed.ac.uk:5000                              |
> | ab49d5060d4746e8b8ce5af5cd0902d0 | RegionOne | keystone     | identity        | True    | internal  | http://10.19.3.200:5000/     
> 
> 
> Greg Blow
>   2 hours ago
> https://bugs.launchpad.net/ceilometer/+bug/1981207
> 
> LaunchpadLaunchpad
> Bug #1981207 “Ceilometer depends on deprecated admin endpoint of...” : Bugs : Ceilometer
> Error occurs on the Devstack (Release Yoga) using the ceilometer plugin:
> --- local.conf ---
> ...
> enable_plugin ceilometer https://opendev.org/openstack/ceilometer stable/yoga
> ...
> ---
> After investigating the ceilometer notification-agent log, keystoneauth1 does not found the admin entity
> ---
> Show more
> 
> 
> Greg Blow
>   2 hours ago
> I think it may be a problem of trying to use the keystone endpoint with the admin interface.
> 
> 
> Greg Blow
>   2 hours ago
> (listing images with the admin interface works)
> 
> 
> Greg Blow
>   1 hour ago
> @Piotr Parczewski
>  
> @Michal Nasiadka
>  I think the ansible/somerville-project.yml playbook (for deploying new projects into openstack through ansible) might be broken. One of the tasks tries to call an admin endpoint for keystone, which doesn't look to exist anymore according to openstack output and some external bug reports. I may be misunderstanding, however.

**Comment by tms-epcc** [comment]
@GregBlow fixed
