### ISSUE TITLE
Install new RAID cards in hypervisor nodes

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#19]
New HPE RAID cards are scheduled to arrive in early June. These need to be installed in the hypervisor nodes to allow faster access to the ephemeral disks.

**Comment by GregBlow** [comment]
If we can enroll new hyprevisors (issue 21) such that there is sufficient capacity for migration without shutdown, and there are no unexpected logistical challenges in migrating/shutting down instances, it should be possible to upgrade the remaining three hypervisors within a single day of focussed work, although update times for software may render this impractical and more reasonable to target a more relaxed two working day schedule. Will schedule once sv-sm-03 and sv-sm-0-4 are confirmed working.

**Comment by GregBlow** [comment]
All work to upgrade hardware in new nodes is completed. Will not close issue as I believe testing still pertains to it. @astrodb
