### ISSUE TITLE
Creation of instances with attached block device OS failing

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#195]
with e.g. 2024-09-30 09:39:21.639 7 CRITICAL cinder [-] Unhandled error: cinder.exception.SchedulerHostFilterNotFound: Scheduler Host Filter InstanceLocality could not be found.

Likely a side effect of:
`
https://git.ecdf.ed.ac.uk/lsstuk-somerville/kayobe-config/-/merge_requests/161/diffs?commit_id=84a1cddd342fb146433005f9bdfed187c0ead92d`

**Comment by astrodb** [comment]
Issue fixed with locatity filter
