### ISSUE TITLE
new instances deployed to sv-hpe-0-10 are not externally accessible.

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#199]
@gpfrancis reports issue:

Hi, I just created an instance (name static-web, id d83f1d45-8b76-4e2c-a7f6-8d7bc15e6687) in project Lasair, assigned a floating IP and it doesn't appear to be reachable. Is there a network problem?

issue resembles problem with sv-hpe-0-8. Verified that applies to test instances created by myself (identical copies of which function on other hosts)

**Comment by GregBlow** [comment]
switch VLAN config identical for port channels corresponding to sv-hpe-0-10 and sv-hpe-0-11

**Comment by astrodb** [comment]
I believe Piotr fixed this. If so, close it?

**Comment by GregBlow** [comment]
Fix reported here:

https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1732265858457929

> Good morning - the issue is resolved now, any downtime is no longer needed. The problem was veth interface was not plugged correctly on the system - I deleted its NM definition & re-run Kayobe networking configuration for the host, which takes care of the veth pair. Since then I was able to ping my instance’s FIP

**Comment by GregBlow** [comment]
compute and volume services are back in.

**Comment by GregBlow** [comment]
repeated original test, now working. Issue resolved.

**Comment by GregBlow** [comment]
Appears to have reoccured with sv-hpe-0-14 on reboot:

```
[root@sv-hpe-0-14 ~]# nmtui

(nmtui:1996060): nm-CRITICAL **: 10:03:43.759: file src/nmtui/nmt-editor.c: line 383 (<dropped>): should not be reached

(nmtui:1996060): GLib-GObject-CRITICAL **: 10:03:43.760: g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed
```

**Comment by GregBlow** [comment]
Greg Blow
  20 minutes ago
looking at Veth p-bridge0-o in nmtui gives a Segmentation fault.




21 replies


Mark Holliman
  [17 minutes ago](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738058846227939?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
can you check it with nmcli commands?


Greg Blow
  [16 minutes ago](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738058950690899?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
[root@sv-hpe-0-14 ~]# nmcli device show bridge0-o
GENERAL.DEVICE:                         bridge0-o
GENERAL.TYPE:                           openvswitch
GENERAL.HWADDR:                         36:29:09:07:C2:45
GENERAL.MTU:                            1500
GENERAL.STATE:                          10 (unmanaged)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
IP4.GATEWAY:                            --
IP6.GATEWAY:                            --
[10:10](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059020937919?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
I get the same segfault on a different hypervisor that does allow external access.
[10:10](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059037739639?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
[root@sv-hpe-0-12 ~]# nmtui

(nmtui:4068597): nm-CRITICAL **: 10:09:24.433: file src/nmtui/nmt-editor.c: line 383 (<dropped>): should not be reached

(nmtui:4068597): GLib-GObject-CRITICAL **: 10:09:24.434: g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed
[root@sv-hpe-0-12 ~]# nmcli device show bridge0-o
GENERAL.DEVICE:                         bridge0-o
GENERAL.TYPE:                           openvswitch
GENERAL.HWADDR:                         BA:30:16:D0:53:48
GENERAL.MTU:                            1500
GENERAL.STATE:                          10 (unmanaged)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
IP4.GATEWAY:                            --
IP6.GATEWAY:                            --


Mark Holliman
  [14 minutes ago](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059054650019?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
That's concerning...and possibly indicates a red herring.


Greg Blow
  13 minutes ago
hypervisor was externally accessible prior to rebooting


Mark Holliman
  [13 minutes ago](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059081316899?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
Yeah, but if the segfault is common to working and non-working HVs, it might not be related to the current issue.
10:12
I recall this happening before, with a different fix. I'll check through the old tickets.


Greg Blow
  12 minutes ago
this is the most recent one I referenced
https://github.com/lsst-uk/somerville-operations/issues/199

[#199 new instances deployed to sv-hpe-0-10 are not externally accessible.](https://github.com/lsst-uk/somerville-operations/issues/199)
[@gpfrancis](https://github.com/gpfrancis) reports issue:
Hi, I just created an instance (name static-web, id d83f1d45-8b76-4e2c-a7f6-8d7bc15e6687) in project Lasair, assigned a floating IP and it doesn't appear to be reachable. Is there a network problem?
issue resembles problem with sv-hpe-0-8. Verified that applies to test instances created by myself (identical copies of which function on other hosts)
Assignees
[@GregBlow](https://github.com/GregBlow)
Labels
bug, hardware, networks, configuration change
<https://github.com/[lsst-uk/somerville-operations](https://github.com/lsst-uk/somerville-operations)|lsst-uk/somerville-operations>lsst-uk/somerville-operations | Nov 19th, 2024 | Added by [GitHub](https://ifaedinburghs-ofn4738.slack.com/services/B030ACPR6SF)


Mark Holliman
  11 minutes ago
OK, did you try that fix?


Greg Blow
  [10 minutes ago](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059264213799?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
deleting the nm config and running a kayobe playbook? No, would require improvisation.
[10:16](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059410899239?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
from sv-hpe-0-12:
p-bridge0-o: connected to p-bridge0-o
        "p-bridge0-o"
        ethernet (veth), D2:80:28:67:86:A9, sw, mtu 9000

p-bridge0-p: connected to p-bridge0-p
        "p-bridge0-p"
        ethernet (veth), EA:A2:9C:6A:D1:1D, sw, mtu 9000
        master bridge0
sv-hpe-0-14 is missing the corresponding pbridge0-p interface.
[10:17](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059452716249?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
I'm not sure:
What deleting the nm config comprises (if I nuke a directory, or certain files)
Which playbook needs running


Michal Nasiadka
  6 minutes ago
[root@sv-hpe-0-14 ~]# nmcli conn up p-bridge0-p
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/14)
[10:19](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059559518109?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
Is it better now?


Greg Blow
  4 minutes ago
looks to be, yes, thank you.
[10:21](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059660495769?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
hold on wait
[10:21](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059667565239?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
yes
[10:21](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059677272669?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
(just wanted to make sure I had the right test)


Michal Nasiadka
  3 minutes ago
p-bridge0-p was down in nmcli conn output
[10:21](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1738059707915429?thread_ts=1738058695.718579&cid=C01Q56Q78LT)
might be some bug in NM in RL9.2
