### ISSUE TITLE
Migrate old HV nodes into new Somerville

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#20]
Once all projects have moved onto the new cloud the old HV nodes can be added to the new cloud. This requires:
1. installing the 100Gbps network cards in them
2. wiping the existing OS
3. racking and cabling them in the new racks
4. setting up the ILO interfaces
5. adding them into the kayobe config
6. deploying the kayobe config to install their OS's and set them up

**Comment by astrodb** [comment]
Waiting help from StackHPC to finalize the first two nodes.

**Comment by GregBlow** [comment]
sv-sm-0-[3,4] appear to be working in Somerville cluster.

**Comment by markgbeckett** [comment]
Woohoo!

**Comment by GregBlow** [comment]
all of sv-sm-0-[0-4] are now racked (though are mislabelled presently, small task to correct when next on site), with the remaining 3 hypervisors pending documenting, switch configuration, cabling, and provisioning.

- [ ] (re)label hypervisors
- [ ] document cabling
- [ ] label cables
- [ ] connect cables
- [ ] configure bmc mgmt switch
- [ ] configure hsn leaf switch
- [ ] configure mgmt switch
- [ ] boot hypervisors by PXE to introduce to bifrost
- [ ] provision
- [ ] deploy

**Comment by GregBlow** [comment]
I also want to modify the arrangement of cables on the SHN switch sv-leaf-2 for greater consistency.

**Comment by GregBlow** [comment]
sv-sm-0-0 and sv-sm-0-2 are both showing faulty DIMMs.

**Comment by GregBlow** [comment]
Currently trying to live migrate instances gives an error:

Error: Failed to live migrate instance to host "sv-sm-0-3". [Details](https://somerville.ed.ac.uk/admin/instances/#message_details)
Migration pre-check error: Unacceptable CPU info: CPU doesn't have compatibility. 0 Refer to http://libvirt.org/html/libvirt-libvirt-host.html#virCPUCompareResult (HTTP 400) (Request-ID: req-a2715b29-f5fa-4b71-a98f-b41a0a8d8ffc)

**Comment by GregBlow** [comment]
https://platform9.com/kb/openstack/live-migration-fails-with-error-unacceptable-cpu-info-cpu-doesn
https://access.redhat.com/solutions/3419521
https://bugzilla.redhat.com/show_bug.cgi?id=1285108

**Comment by GregBlow** [comment]
Test cold migration via cli..

**Comment by GregBlow** [comment]
Ongoing network issues.

**Comment by GregBlow** [comment]
differences noted so far:

1. Seems to be many additional interfaces with names prefixed 'tap' on the sv-hpe hypervisors, and a few on some supermicro hypervisors. Based on the pattern, I imagine these are generated by openstack and not indicative of how a fresh hypervisor should look
2. The other significant difference is in the naming of interfaces. on the sv-hpe hypervisors we have ens10f0np0, which has the equivalent interface named eno1 on the supermicro hypervisors

**Comment by GregBlow** [comment]
Instances now deploy properly to supermicro hypervisors without specific fix being implemented.

**Comment by GregBlow** [comment]
Nodes have started working without a specific fix being identifiable. Will run QServ development machines on this AZ until redeployment to monitor stability.
