### ISSUE TITLE
Local account provsioning for Roy Williams

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#201]
Provide a local account for Roy Williams to facilitate access during IRIS-IAM outage.

**Comment by RoyWilliams** [comment]
Actually I have an account, but its no good. 
Username is royw and I have the password.
But when I am logged in I can't see anything:
```Error: Unable to retrieve instances. 
Policy doesn't allow os_compute_api:servers:detail to be performed. (HTTP 403) 
```

**Comment by GregBlow** [comment]
I've updated your permissions on `royw` to match those of user `RoyWilliams`. Can you try again please?

**Comment by RoyWilliams** [comment]
Hooray! Thank you Greg!
