### ISSUE TITLE
Schedule migration of old cloud nodes into Somerville

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#21]
Plan the steps and deadlines for adding the old cloud nodes into the new Somerville deployment.

**Comment by GregBlow** [comment]
switch configuration done, nodes appear to PXE boot successfully. Need to complete cluster integration.

**Comment by GregBlow** [comment]
(sv-sm-0-[3,4])

**Comment by astrodb** [comment]
old hv's integrated, ceph nodes migrated into racks.
