### ISSUE TITLE
Request IAM token expiration extension

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#40]
Ask IRIS IAM team about extending IAM token expiration to extend beyond scheduled downtimes.

**Comment by astrodb** [comment]
George will email IAM team this week.

**Comment by markgbeckett** [comment]
Have emailed Thomas Dack (IRIS IAM contact) to socialise the idea. Waiting on a response.

**Comment by markgbeckett** [comment]
Tom Dack has confirmed he will add the suggestion to the agenda for the next IRIS IAM meeting.

**Comment by astrodb** [comment]
They said no.
