### ISSUE TITLE
Heat may not be working

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/somerville-operations#42]
Attempting to deploy a heat template results in a 500 error with no useful error message.

**Comment by markgbeckett** [comment]
In case it is useful for diagnosis of the issue, StackHPC has advised that OpenStack Placement (https://docs.openstack.org/osc-placement/latest/) provides a more accurate report on the provisionable resources than the Horizon Dashboard.

**Comment by RoyWilliams** [comment]
This was my mistake. I mixed up openrc.sh and application.sh which both come from horizon -- but opposite corners of the web page -- and the text oof the file is almost the same. Also the error message from the switch is content free, just says Internal Server Error.
