### ISSUE TITLE
Add QUB to SSH whitelist 

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/somerville-operations#43]
Please add QUB and any other IP address ranges used by @genghisken and @thespacedoctor to the SSH whitelist.

**Comment by GregBlow** [comment]
@genghisken @thespacedoctor 

Please run curl ipconfig.io while connected to your institution VPN and post the output here.

**Comment by genghisken** [comment]
I work a lot from home, but I guess it's pointless giving you my BT IP addresses, since they'll change regularly. I can jump through QUB if necessary using an SSH config entry.

**Comment by GregBlow** [comment]
I've requested the entire QUB range (143.117.0.0) be given access. It would be ideal to narrow this down at some point. 

When working from home do you not connect to an institutional VPN for any QUB services?

**Comment by genghisken** [comment]
Weirdly, no. We seem to be about the only department that doesn't use that setup.  I suspect that will change soon!

**Comment by GregBlow** [comment]
Firewall rules updated. Would you be so good as to test and confirm that you can SSH from a QUB address?

**Comment by genghisken** [comment]
Yes - access from QUB now works. Many thanks!

**Comment by GregBlow** [comment]
Great. Please let us know if any other addresses need adding to the access list.

**Comment by markgbeckett** [comment]
Thanks for sorting this out so swiftly, @GregBlow
