### ISSUE TITLE
Deploy local SSDs in migrated HVs for Gaia

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#46]
- [x]  Check old HVs for PCIe availabilty
- [ ]  Choose/order NVMe SSDs
- [ ]  Install SSDs in old HVs
- [ ]  Add Flavour that offers SSD as local mount for Gaia project

**Comment by GregBlow** [comment]
The sample server examined had a Super RSC-R1UW-2E16 riser card with a spare slot (the other of two used for a 2 port 56Ge network card, Model Number CX414A, ConnectX 44= 40/56GbE, no manufacturer seen).

https://www.amazon.com/Supermicro-RSC-R1UW-2E16-Riser-Card/dp/B00832VPME

Space is limited. See attached images.

![WIN_20221014_14_02_43_Pro](https://user-images.githubusercontent.com/2021333/195855309-b14016af-b8b3-446d-b9c0-4ff894631d04.jpg)
![WIN_20221014_14_10_00_Pro](https://user-images.githubusercontent.com/2021333/195855316-464de5e3-6f12-4d2f-98dd-54888ca7b759.jpg)

**Comment by GregBlow** [comment]
Note: Had to break the anti-tamper seal sticker to examine.

**Comment by astrodb** [comment]
Hardware to purchase and install: https://uk.insight.com/en_GB/shop/product/SSDPEKNW020T8X1/INTEL/SSDPEKNW020T8X1/Intel-SolidState-Drive-660p-Series--SSD--2-TB--PCIe-30-x4-NVMe/

I'll ask George to put in the PO.

**Comment by astrodb** [comment]
Adapters and SSDs installed, HVs online
