### ISSUE TITLE
Creat Gaia project and onboard users

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#48]
Create Gaia project, with Dave Morris (dmr@roe.ac.uk) as main point of contact.

Setup limited quotas to start so they can begin tests with their K8 deployment.

**Comment by astrodb** [comment]
Project name: roe-gaia-jade
Members: Dave Morris, Stelios Voutsinas, Amy Krause

**Comment by astrodb** [comment]
Greg, can you get this project added into the deployment config and created? Give it limited quotas for now: 10 instances, 40 cores, 100GB RAM, and 50TB volumes.

Contact dmr@roe.ac.uk for the IAM login details, as he's the main project contact.

**Comment by GregBlow** [comment]
https://git.ecdf.ed.ac.uk/lsstuk-somerville/openstack-config/-/merge_requests/49

**Comment by GregBlow** [comment]
Gaia project is instantiated. Still needs an IRIS IAM group setup and affiliated to be useful.

**Comment by GregBlow** [comment]
https://git.ecdf.ed.ac.uk/lsstuk-somerville/kayobe-config/-/merge_requests/48

**Comment by GregBlow** [comment]
IRIS IAM group esa/gaia affiliated with somerville appropriately.

**Comment by GregBlow** [comment]
renaming to somerville-gaia-jade, also using as opportunity to test degree to which project can be changed.

**Comment by Zarquan** [comment]
Interesting to know how difficult/easy it was to make the change ?

**Comment by GregBlow** [comment]
As it was a brand new project I killed the original one and recreated it from config, which took some computer time, but in terms of my attention was pretty minimal (changed a few parameters in config, reran git and ansible from history). For a project that had content that would prevent deletion I would have been able to change some labels, but not the project ID. This latter option, not taken, would have been faster but not as neat.

As a third option, it may have been possible to properly change the project id, but that would have required more time than simply recreating. Probably worth looking at if the project had been more mature though,
