### ISSUE TITLE
Wiki page for firewall troubleshooting tips

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#50]
Users have requested a wiki page with instructions on how to troubleshoot firewall issues - taking them through the different layers (ACF, OpenStack Security groups, localhost).

**Comment by GregBlow** [comment]
Suggestion for contents:

nmap and it's basic use, comparing hosts in different tiers (user computers on VPN or not, instances within openstack, etc)

use of security groups to gate traffic within a project (from other security groups) or to a wider range (using CIDR rules).

**Comment by astrodb** [comment]
Wiki page complete: https://github.com/lsst-uk/somerville-operations/wiki/Network-Troubleshooting
