### ISSUE TITLE
Bastion host for remote user login

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#51]
Investigate deploying a bastion host on Somerville (possibly as an instance within a dedicated project) which users can utilize for SSH hopping through the firewall. 

The machine will need a public IP, should implement failtoban to limit intrusion attempts, and will need to have accounts/keys added on request by users.

**Comment by GregBlow** [comment]
@DP-B21 Would you be so good as to set up a 'systems' project using this SOP:

https://www.wiki.ed.ac.uk/pages/viewpage.action?pageId=513447460

You can safely go as far as modifying the configs in gitlab, if you use past commit as a template (e.g. https://git.ecdf.ed.ac.uk/lsstuk-somerville/openstack-config/-/commit/c7d48fc9f449489dc0846da5aa88a63a2fb4ab5d) you can see how. But I'll be in touch and we can work through. 

It should have it's own quota, and use the same values as the sandbox quota. Thank you.

**Comment by astrodb** [comment]
Priority has increased due to Chris F's student not having access to a static IP.

**Comment by GregBlow** [comment]
Note: Chris has indicated that "Don't worry about working too hard on the jump host. Harry and I will find a solution."

I'd still like to get it done sooner rather than later, though.

**Comment by astrodb** [comment]
Might be worth asking them if the student has a login to a Uni server down there. If so, we could add that IP.

**Comment by astrodb** [comment]
I will set this up on one of the older LSST testbed machines at ROE.

**Comment by GregBlow** [comment]
Since it's at ROE, it won't need any fresh holes poking in the ACF firewall?

**Comment by astrodb** [comment]
Correct. It'll sit in the 192.41.108.x subnet, which already has SSH access to Somerville's public range.

**Comment by astrodb** [comment]
Bastion host deployed at ROE on repurposed LSST test server. 

Rocky9, fail2ban setup on SSH using firewalld

Host: 192.41.108.40

**Comment by astrodb** [comment]
@GregBlow Can you create a DNS entry for it? 
Something like: bastion.somerville.ed.ac.uk
Pointing to: 192.41.108.40

**Comment by GregBlow** [comment]
requested under I230907-3311

**Comment by astrodb** [comment]
Seems to be done. Closing this.
