### ISSUE TITLE
Redesign log retention schema

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#55]
Short term:

Automatic culling of logs based on available disk space remaining?

Long term: 

Export to ACF infra hosts for long term retention.

**Comment by GregBlow** [comment]
100s of lines of bash logs per second being generated.

**Comment by GregBlow** [comment]
sample of log size from sv-ssd-0-7
```

-rw-------   1 root   root   1360836810 Nov  3 16:41 messages
-rw-------   1 root   root   2092053724 Oct  9 03:10 messages-20221009
-rw-------   1 root   root   2108355606 Oct 16 03:43 messages-20221016
-rw-------   1 root   root   2101061322 Oct 23 03:40 messages-20221023
-rw-------   1 root   root   1976830129 Oct 30 03:32 messages-20221030
```

**Comment by GregBlow** [comment]
https://stackoverflow.com/questions/34281643/how-to-test-whether-log-compaction-is-working-or-not-in-kafka

**Comment by astrodb** [comment]
Enabled zipping of logs, problem solved.
