### ISSUE TITLE
Address chronic alerting of slow MySQL on sv-ctrl-0

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#56]
Most common alert, not associated with any service affecting results. Need to determine if alert needs to be less sensitive or issue requires investigation to remedy problem.

**Comment by GregBlow** [comment]
https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Slow_queries

**Comment by astrodb** [comment]
This appears to have stopped. Closing issue for now.
