### ISSUE TITLE
Create QServ iris-iam group and keystone association

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#58]
Group lsst/qserv requested with gblow and mholliman as initial approvers/users.

**Comment by markgbeckett** [comment]
Can I check that setting up separate allocation group for Qserv won't impact on how RSP connects to Qserv? Do we need to be careful about security-group settings or similar?

**Comment by GregBlow** [comment]
good point. I don't think so but will check before creating association when I get a bit more time.

**Comment by GregBlow** [comment]
Currently no mappings to qserv, so I don't think it will be an issue. 

Additional: Not sure if RSP _should_ have access to QServ Openstack resources or simple access to QServ services (database). Please consider and feedback. @markgbeckett

**Comment by GregBlow** [comment]
Done, but need to troubleshoot RSP. Will do on separate issue.
