### ISSUE TITLE
Troubleshoot iris-iam RSP group:project affiliation

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#59]
reported by @markgbeckett, membership of both qserv and rsp groups only confers access to Qserv project.

**Comment by GregBlow** [comment]
membership of only lsst/rsp fails to grant access to Somerville at all. 

Response:
`
{"error":{"code":401,"message":"The request you have made requires authentication.","title":"Unauthorized"}}`

Suspect config is broken.

**Comment by GregBlow** [comment]
RSP block is not touched by the single edit that attached Qserv group to project. Multiple other similar blocks apparently intact and functioning.

**Comment by GregBlow** [comment]
was premature, RSP assocation works (apparently) correctly for me, but has rendered a further apparent wrinkle: revocation of all iris-iam groups appears to prevent access to Somerville at all, however removal of a subset of member groups does not remove membership in keystone from those groups.

**Comment by GregBlow** [comment]
hypothesis: I wonder if it's an issue that the most recent group in the config is the only valid one and it has only been noticed because so far each new group has had all its users inducted before the creation of the next?

**Comment by GregBlow** [comment]
no, removing my user gblow from each project membership manually and then trying to log in using IRIS IAM gives me access to only RSP project (which is correct)

**Comment by GregBlow** [comment]
@markgbeckett please confirm that issue is extant?

**Comment by astrodb** [comment]
@GregBlow will request @markgbeckett get added and removed from the group to see if this solves it.

**Comment by GregBlow** [comment]
other way around, but yes.

**Comment by markgbeckett** [comment]
How shall I request to have my RSP affiliation removed? Ticket to IRIS IAM helpdesk? I took a look around the IRIS IAM web interface but didn't see anything obvious.

**Comment by markgbeckett** [comment]
@GregBlow Would you like me to apply to join lsst/rsp group on IRIS IAM to see if my authorisations are updated on Somerville? Also, I can still see Qserv resources on Somerville, 24 hours after I was removed from the lsst/qserv group on IRIS IAM.

**Comment by GregBlow** [comment]
Closing this ticket. Readding George to the RSP group before QServ group added to the correct keystone group appropriately. In lieu of an indicative pattern or a chronic problem leaving this unsolved for now.
