### ISSUE TITLE
Renew somerville.ed.ac.uk cert

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#63]
https://stackhpc.github.io/openstack-admin-guide/operations_and_monitoring.html#installing-and-updating-tls-certificates

To update an existing certificate, for example when it has reached expiration, change the value of secrets_kolla_external_tls_cert in `/home/stack/kayobe/src/kayobe-config/etc/kayobe/environments/somerville` and run the following command:

`kayobe# kayobe overcloud service reconfigure --kolla-tags haproxy`

**Comment by GregBlow** [comment]
Next needed Tue, 07 Nov 2024

**Comment by GregBlow** [comment]
Running through process with Daniel Pizarro.

@DP-B21 Could you write up as SOP please and I will review?

**Comment by GregBlow** [comment]
New certificate applied. Valid until 17th Nov. 2025.

**Comment by DP-B21** [comment]
Hi @GregBlow the SOP has been written, however the final steps have not been concluded, could you please review it in the meantime? -  https://www.wiki.ed.ac.uk/pages/viewpage.action?pageId=665977700

**Comment by GregBlow** [comment]
Thank you, I've given it an editorial pass and am happy to publish it as complete.
