### ISSUE TITLE
Confirm consumables required for 2022/2023 Somerville expansion

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/somerville-operations#64]
Provide a list of items that we need to order (in addition to HPE order) to integrate new Ceph storage and compute nodes into Somerville.

**Comment by astrodb** [comment]
11 x Cat6 Ethernet Cables
11 x Cat5 Ethernet Cables

Cable lengths/counts to be checked by @GregBlow to ensure they can reach the necessary switches

**Comment by GregBlow** [comment]
7 * 3m, 4*5m  Cat6
7 * 5m, 4* the next size up? This might be 10m, should be at least 7m Cat5

(Both are inter-rack links)

**Comment by markgbeckett** [comment]
Order request submitted to SoPA Helpdesk.

**Comment by markgbeckett** [comment]
Order has been submitted. Cables should be delivered direct to ACF (FTAO @GregBlow ).
