### ISSUE TITLE
Provide alternative route for SSH connections to services running on Somerville

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/somerville-operations#67]
Somerville restricts in-coming SSH connections to certain IP ranges, for security reasons. For UoE, this means the published VPN range. Other institutions may have similar ranges. Because it takes some time to set up new IP ranges (e.g., for new institutions or changed institutional ranges), managers of Somerville-hosted services may not be able to connect to their services when they need to.

To work around this, alternative access should be considered. For example:
- Setting up a Bastien host via which people can connect
- have the SSH daemon listen on an additional non-default port in the default images and open this port (rather than 22)
- enable SSH at the firewall level, but disable by default at the security group level (users can then re-enable themselves for specific instances)
- enable SSH, but with a rate limit at the firewall to prevent brute force attacks, e.g. max 5 new connections per minute from the same source IP

**Comment by gpfrancis** [comment]
I think we did previously agree to set up a bastion host for this, and a process for adding new user accounts to it, but this has not been done yet.

**Comment by astrodb** [comment]
Duplicate of: https://github.com/lsst-uk/somerville-operations/issues/51

**Comment by markgbeckett** [comment]
Sorry, I missed the existing ticket!
