### ISSUE TITLE
Create official VDFS Project

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#69]
WFAU will start migrating completed astronomy archive projects to Somerville now, starting with the OmegaCam Science Archive (OSA). After that will come the VISTA Science Archive (VSA)(migration starts in Q3 2023) and the WFCAM Science Archive (WSA)(migration starts in Q3 2024). In total these archives will comprise multiple PB of data, both flat file and database. There will be multiple web server VMs with public IPs and multiple database VMs on a private LAN.

For administrative purposes it makes sense for all three of these archives to reside in a single project, since the same team of people will be running them. 

Starting quota will be for the OSA alone (we can expand later when VSA migration begins later this year):
Instances - 10
CPUs - 12
RAM - 24GB
Volumes - 10
Volume Storage - 180TB
Floating IPs - 2

The 180TB of storage will only fill up slowly as data is copied across, and I don't expect it to complete before the new Ceph nodes arrive.

**Comment by GregBlow** [comment]
@astrodb  Does the scope of this request encompass setting up an IRIS IAM group as well at this point or just the openstack side?

**Comment by astrodb** [comment]
Let's just leave it on the OpenStack side for now. We can setup the IAM group later once I have moved the first archive over.

**Comment by GregBlow** [comment]
@astrodb Very good. Any requirements for setting up networking or would you like to do that yourself?

**Comment by GregBlow** [comment]
Very good, I'll close off this issue as I believe that should be the thing in it's entirety. Feel free to reopen and ping me if anything else.
