### ISSUE TITLE
Horizon dashboard is running old version of Python, potentially increasing service vulnerability

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/somerville-operations#7]
JISC has flagged a potential issue with version of Python running on Somerville's Horizon service. The version is considered old and implicitly more vulnerable. 

Investigation has confirmed this is a requirement for current OpenStack version, but that the version is supported by Red Hat. 

There are no current vulnerabilities published for this Python version, plus Somerville Sys Admins will continue to monitor security channels in case of vulernabilities.

Further, we will update the Horizon-service config, to hide details of Python versioning from Internet clients.

**Comment by GregBlow** [comment]
now on 3.9:

```
[Fri Jan 05 13:25:22.669544 2024] [wsgi:error] [pid 23:tid 117] [remote 10.19.3.10:34430] /var/lib/kolla/venv/lib/python3.9/site-packages/oslo_policy/policy.py:1119
```
