### ISSUE TITLE
pulp container appears to be full of artifacts

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#70]
Detected by secondary effect of sv-seed-vm-0 losing functionality due to messages log inflation due to pulp container filling. e.g. 

Jan  8 23:24:17 sv-seed-vm-0 dockerd[1569]: time="2023-01-08T23:24:17.128035356Z" level=error msg="Failed to log msg \"\" for logger json-file: error writing log entry: write /var/lib/docker/containers/ac0c77a6b9994492c340727e286895792b15418d1cbfd537a855cf0867d34532/ac0c77a6b9994492c340727e286895792b15418d1cbfd537a855cf0867d34532-json.log: no space left on device"
Jan  8 23:24:17 sv-seed-vm-0 dockerd[1569]: time="2023-01-08T23:24:17.128426598Z" level=error msg="Failed to log msg \"\" for logger json-file: error writing log entry: write /var/lib/docker/containers/ac0c77a6b9994492c340727e286895792b15418d1cbfd537a855cf0867d34532/ac0c77a6b9994492c340727e286895792b15418d1cbfd537a855cf0867d34532-json.log: no space left on device"

from pulp container (not sure what is with hostname)

[root@sv-seed-vm-0 /]# df -h /
Filesystem      Size  Used Avail Use% Mounted on
overlay          98G   98G     0 100% /

/var/lib/pulp/media/artifact comprises ~97% of disk usage.

**Comment by GregBlow** [comment]
`[root@sv-seed-vm-0 /]# df -h
Filesystem                        Size  Used Avail Use% Mounted on
overlay                            98G   98G     0 100% /
tmpfs                              64M     0   64M   0% /dev
tmpfs                             7.8G     0  7.8G   0% /sys/fs/cgroup
shm                                64M     0   64M   0% /dev/shm
/dev/vda1                          20G   19G  1.8G  92% /etc/pulp
/dev/mapper/data-docker--volumes   98G   98G     0 100% /etc/hosts
tmpfs                             7.8G     0  7.8G   0% /proc/acpi
tmpfs                             7.8G     0  7.8G   0% /proc/scsi
tmpfs                             7.8G     0  7.8G   0% /sys/firmware`

**Comment by GregBlow** [comment]
kolla logs in docker filesystem were full

**Comment by markgbeckett** [comment]
Good catch. Is there something we can do to prevent this happening again, or to quickly detect and address it?
