### ISSUE TITLE
Request to increase resources on RSP project

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/somerville-operations#72]
We are running close to the limit of resources on the RSP project, as @gpfrancis & myself (@stvoutsin) and would like to double the existing resources to allow room for 4 Kubernetes clusters running simultaneously (2 dev 2 production clusters).
Specifically, the resources to be doubled (if available) would be:
CPU / RAM / Floating IPs / Security Groups / Security Group Rules & Routers

**Comment by GregBlow** [comment]
Good afternoon Stelios,

We'll accomodate once there are sufficient resources, but this may not be until the new hypervisor hardware arrives as Somerville is presently running close to the maximum capacity of the existing 4 HPE hypervisors.

Regards,

Greg

**Comment by GregBlow** [comment]
Original request completed, with modification of setting security groups/security group rules to infinite rather than 40 and 400 respectively.
