### ISSUE TITLE
Create service incident reponse procedure

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#76]
Write up an publish an incident response procedure for Somerville. Point it out to StackHPC so they know to follow it.

**Comment by GregBlow** [comment]
Important considerations from my point of view:

Collision avoidance
Determining threshold for triggering a response

**Comment by astrodb** [comment]
Work in progress: https://github.com/lsst-uk/somerville-operations/wiki/Cloud-Service-Incident-Response-Procedure

**Comment by astrodb** [comment]
Policy defined, awaiting feedback.
