### ISSUE TITLE
Increase Qserv project quota

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#84]
Having consulted with the developers they've recommended an expansion of the spec from what Craig Manzi deployed (and a significant step up from the current cluster, which was downsized when the number of vCPUs across the cluster was constrained by the absence of overcommit). 

What is recommended is 1 * Czar node:

32 vCPU, 128GB RAM, 50GB root disk, 5TB data volume (data volume up from 1TB)

2 * Utility node:

(specs are per node)
32 cores (up from 4), 128GB RAM (up from 16GB), 50GB root disk, 5TB data volume

10 * Worker node

(specs are per node)

32 cores (up from 8), 128GB RAM (up from 64GB), 50 GB Root disk, 5TB data volume.

Part of the suggestion is to have a standard flavour across all nodes (although this seems predicated on running baremetal). Adding 296 vCPUs represents more than doubling the current total QServ project quota, with a similar impact on RAM. I think before this is finalised:
1.	Mike Read should be consulted as to how performant Craig Manzi's cluster was, before and after I downgraded it (if he remembers). 
2.	What the maximum budgetary allocation for QServ should look like.
Due to the nature of QServ, it's possible to add worker nodes as additional capacity is required. I'd still like to perform some experiments simulating element failures to determine what is 'safe', however as I am not a user of the system I do not think I can give an educated estimation about what 'performant' looks like to push back on what looks to be a significant increase in spec. 

If the presumption is that the nodes are bare metal, then it's plausible the developers glossed over the relatively low data volume figures I provided. They've also recommended NVMe SSD rather than HDD, but I am skeptical of the economic argument for this given the current architecture and load balance of Somerville. 

Following some experiments with node resiliency I can try reprovisioning nodes so that we have flexibility, but I don't think this impacts the core question of how much resource QServ is allocated.

**Comment by GregBlow** [comment]
Current consumption on QServ project is 152 vCPUs and 964.2GB RAM. Production cluster represents 416 vCPUs and 1664GB RAM.

**Comment by GregBlow** [comment]
We'd max out cluster RAM (total capacity=4TB) if this is implemented. I think we need to cut worker RAM by half (to original value of 64GB each), and perhaps deploy with a reduced worker count to begin with.

**Comment by GregBlow** [comment]
new flavors deployed via config, however am noting that assigning projects does not work correctly (does not remove from manually created flavor)

**Comment by GregBlow** [comment]
Guidance provided by Igor Gaponenko:

Igor Gaponenko
  [3 days ago](https://lsstc.slack.com/archives/C39113B9C/p1678472898189409?thread_ts=1678463662.094629&cid=C39113B9C)
Hi 
[@Greg Blow](https://lsstc.slack.com/team/U03Q2BKGTDG)
!A few comments on the specs. The data volume for czar should be bigger. This filesystem is meant to store the following data:
- so called "director" index tables (in MariaDB/MySQL) of the production catalogs. Each such index could be very large for the multi-billion row catalogs. For example, the Object table of LSST full-Sky DP release would have 20 billion objects (rows). Each such row may require 64 + 32 + 32 = 128 bytes for data. Plus various overheads imposed by the MySQL's InnoDB engine. So, you may easily end up with 0.5 TB for one index table alone. And you may have other catalogs here as well.
- intermediate results of the on-going queries. Some queries may produce a few GB of data. And you may have many of those being processed by Qserv in parallel. The amount of data in this category might reach 100 GB (depending on a load to Qserv) or even higher.
So, I would recommend increasing the size of this volume to 5TB.
My next comment is about utility nodes, where I think 16 GB of RAM is way too short. Many services that are going to be run on those node may consume quite a bit of memory. My recommendation would be to bump the number to 128 GB. I would also increase the core count to at least 16.
The number of cores on the worker machines is too low. You should be looking at 32 cores. Some queries might require a lot of CPU for processing. A good example would be the so called near-neighbor that are doing the Cartesian product on the sub-chunks against temporary in-memory (’materialized”) tables. Worker memory is okay, However, I would consider 128 GB here. When processing so called scan or shared scan queries Qserv would preload the relevant table sin memory. Some tables might be as large as 10 GB. And the could be a few of those. With 64 GB of RAM, especially in Kubernetes where you won’t have swap enabled you may ru into the OOM situation (and crashes of the workers).
My general recommendation is to come up with the unified node specs (like 32 cores, 128 GB RAM, and 5 TB disk for service & utility nodes). This would work for all services. And this would give you a flexibility to repurpose the nodes later. It would be also wise to have 2-U nodes with the large number of disk slots to allow expanding storage (adding more disks) later. I would also recommend starting with fewer larger nodes and expand the cluster later if needed.
Also, I’m not sure what type of the disk storage you’re looking at, if it’s going to be based on the traditional HDD or SSD/NVMe. For database applications please consider NVMe. NVMe + high core count would give you the most balanced architecture for running database services.
Regarding your question on “Once completed is it possible to add further worker nodes subsequently?“. The answer is yes, Qserv can be expanded to use more nodes. The built-in data replication service will notice extra nodes and redistribute (rebalance) data across the cluster.
Re: “redundancy”, Qserv has the built-in replication system. You may configure the number of replicas that you want. By default you have a single copy of each table. Note that if you set the replication factor to 2 then you will have 2 copies of each table. You would need to take into account this when planing your storage at the worker nodes.

**Comment by GregBlow** [comment]
Revised:

416 vCPUs 1024 RAM

I'm going to shelve the existing production cluster to free capacity.

**Comment by GregBlow** [comment]
shelving does not reduce usage. I'm going to set vCPU quota to 600 and RAM quota to 2TB.

**Comment by GregBlow** [comment]
I have increased QServ quota as follows:

| ram                  | 2097152
| cores                | 600

When the old production environment is retired, aim is to reduce ram quote to 3/4 and cores to 2/3 of the above. Closing until then.
