### ISSUE TITLE
S3 for Lasair

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/somerville-operations#88]
I would like to try S3 for storing cutout images for Lasair. I am looking here
https://docs.ceph.com/en/quincy/radosgw/s3/python/
where it says
- access_key = 'put your access key here!'
- secret_key = 'put your secret key here!'

Where can I get these keys?

**Comment by RoyWilliams** [comment]
Any progress on this?

**Comment by GregBlow** [comment]
Hello Roy,

Apologies, I havn't had a chance to work through this yet myself. I'll try and get to it soon. In the meantime I think @stvoutsin may have a working solution to S3 implementation and can perhaps help?

Regards,
Greg

**Comment by astrodb** [comment]
I believe this is resolved. Post here before Friday if not, otherwise it will be closed then.
