### ISSUE TITLE
Lasair project CephFS performance issues

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#89]
Roy reports:

Dave, Gareth, Ken, Mark,
Am fighting a cold today, but this morning found the cephfs I/O tangled up. See below. It s running only (1) now, and at a very low rate.

Is there some way to restart the cephfs demon or something? Its so slow now its useless.

Its doing 50 alerts a minute, which should be 3000!
    https://lasair-ztf-svc.lsst.ac.uk/d/iILmd8-Wz/alerts?orgId=1&from=now-3h&to=now

Should we just forget cutouts from now on so that Lasair-ZTF can perform fast? Would be a shame with Matt Nichol starting a whole new research line based on them.
Roy

----------------------
07.35 Lots of processes doing the CephFS
    (1) ingesting to newfits -- looking pretty slow, 200 alerts per minute
    (2) converting fits to doublefits -- not even half way done after 11 days
    (3) moving newfits to fits -- starts 15.00 every day. Should take an hour,
        but there were three still running, from last three days!

Cephfs size = 20T of which used = 7.5T

07.48 I have killed (2) and (3) to see if the alert rate can go up

07.58 Event rate did not go up. I stopped the ingestion, started operation (3) see if it can can complete in a couple of hours.

08.48 Only got to 1% in the first 50 minutes. Stop that then. Comment out the crontab.

08.50 Start the ingest into newfits. No other processes running.

==========================
Complaints from the ingest module found this morning.
Killed with traceback showing it is trying to write to Cephfs

-- Lots of these on the stderr of the writing process An exception of type WriteTimeout occurred. Arguments:
('Error from server: code=1100 [Coordinator node timed out waiting for replica nodes\' responses] message="Operation timed out - received only 0 responses." info={\'consistency\': \'LOCAL_ONE\', \'required_responses\': 1, \'received_responses\': 0, \'write_type\': \'SIMPLE\'}',)

-- When killed, job is hung in the open file of cephfs ^CTraceback (most recent call last):
... snip ....
  File "/home/ubuntu/lasair4/pipeline/ingest/../../common/src/objectStore.py", line 77, in putObject
    f = open(filename, 'wb')
KeyboardInterrupt

**Comment by RoyWilliams** [comment]
Thanks for your help Mark
Both of your keys are already in the bootstrap node `lasair-ztf-bootstrap` both keys, rsa-key-20180904 and euclid-mark. You need to login there first:
`$ssh ubuntu@192.41.122.151`
From there you can get to `lasair-ztf-ingest-0`, the machine doing all the slow file writing.

**Comment by RoyWilliams** [comment]
Hi Mark and Greg
Monday morning was when I saw how slow the system was running, and shut down some long-run copying jobs. And this morning (Weds) the filesystem is performing better (see image below). Now I am reading about how Ceph works[1][2], and I see phrases like "If the data pool is in a NEARFULL condition", "hot and cold tiers", "cache pool". So I wonder if files have migrated to cold store over the last 2 days, so the datapool/cache now has enough space to work effectively?

On another matter[1] how can I run the "ceph" commands to see what it is doing? When I try on the Lasair-ztf bootstrap node, I get "RADOS object not found".
Thanks
Roy

[1] https://docs.ceph.com/en/quincy/cephfs/troubleshooting/#slow-stuck-operations
[2] https://tracker.ceph.com/projects/ceph/wiki/7_Best_Practices_to_Maximize_Your_Ceph_Cluster's_Performance

![Screenshot 2023-04-12 at 12 52 33](https://user-images.githubusercontent.com/8886481/231449489-6c7a0b1d-8e1b-48c5-8868-edf3f40553b8.png)

**Comment by RoyWilliams** [comment]
Looking better this morning
![Lasair rates2023-04-15](https://user-images.githubusercontent.com/8886481/232207599-fa966455-74de-4ebd-8020-e6a318baca8c.png)

**Comment by astrodb** [comment]
Problem appears to be the result of CephFS not being able to cope with the ingest activities running simultaneously with the reorganization of the already existing over-saturated directories. 

Short term plan is try to perform the reorganization on the backup Ceph system (once available).
Long term plan is for LSST event monitoring to use the RADOS object store.

**Comment by astrodb** [comment]
Greg and mark to get system online for transfers.

Gareth will chat with Lasair team to see if it's worth pursuing.

**Comment by RoyWilliams** [comment]
Thanks but I think life is too short. A month ago we made a new space where the cutout images have been going -- only 4000 in each directory so far, whereas there are 80000 in each of the old directories. Therefore we should be able to keep the lasair-ZTF going until Sept 2024 when the whole thing shuts down. 

As for the Lasair-LSST that we are building now, we have permission to keep only that most recent 3 months of cutouts, and have built a suitable directory structure and reaper, and so CephFS will do us well for that future.
