### ISSUE TITLE
timeout=30 on ztf.grafana request

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/somerville-operations#90]
[This call to the requests library](https://github.com/lsst-uk/lasair4/blob/main/pipeline/filter/counts.py#L91-L92) should have `timeout=30` 

It asks uw.edu about how many alerts it thinks there have been today. Last week the entire pipeline stopped because of waiting for this call to complete.

**Comment by astrodb** [comment]
Is this a Somerville issue, or a Lasair issue?

**Comment by RoyWilliams** [comment]
Ooops wrong repo -- sorry Mark!
