### ISSUE TITLE
Create Sandbox project

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#91]
We should have a sandbox project with minimal resources but easy access for people to familiarize themselves with Somerville. 

Starting resources should be like:
Instances: 5
Cores: 16
RAM: 32GB
Volume storage: 2TB

Initial members can be Greg, Mark, Amanda. People can be added later on request.

**Comment by GregBlow** [comment]
I'll also add Daniel Pizarro to the project. It will be a good environment for getting the foundation for QServ development I'd like him to develop.

**Comment by GregBlow** [comment]
sandbox created
