### ISSUE TITLE
Somerville Object Storage support needs to be documented

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/somerville-operations#92]
From Slack discussion:

1: I was just wondering if you had any notes on what you did to get s3 working?
2: I remember I used the Horizon dashboard to create the containers, and then I had to create an API key to use for writing to the container. That if I remember correctly was also done via the dashboard (Horizon - Identity - Application Credentials)

1: Yes - I've also got about that far. I can use the swift API to create and interact with containers and I can get an API key. The main thing I'm missing next is the URL for the S3 endpoint?

2: The base url should be https://somerville.ed.ac.uk:6780/ but you should be able to get a public access link to the bucket / container you've created under Horizon / Containers / Click on container and it shows some metadata including a Public Access link

1: That's interesting - that's the same as Swift. How does it know whether I want to talk to it using the Swift or S3 protocol?
Ah - I see now - the URLs that you get from Horizon are for swift - and also don't appear to work - but if you take the swift part out then you get a URL that returns an S3 format bucket listing
e.g. https://somerville.ed.ac.uk:6780/gftest2 https://somerville.ed.ac.uk:6780/gftest2/hello.txt
Thanks! I think that's given me enough to carry on with for now.

2: Yes I think that's right, Is that working ok for you?

1: So far. I still haven't tried authenticated access using S3 rather than Swift so that's next on the list...
Do you have a preferred S3 CLI interface for testing?
Well it looks like it works with the python aws cli anyway.
$ aws --profile=ceph --endpoint=https://somerville.ed.ac.uk:6780/ s3 mb s3://test3
make_bucket: test3
$ openstack container list
+---------+
| Name    |
+---------+
| test  |
| test2 |
| test3 |
+---------+

**Comment by astrodb** [comment]
Documented here: https://github.com/lsst-uk/somerville-operations/wiki/Object-Store
