### ISSUE TITLE
Admin node data volume amendment to add redundancy 

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#96]
To accomodate upgrade work and disk space issues a single 1TB disk was added to sv-admin-0. As it is RAID 0 this volume is at risk of failure, but with backups does not present critical risk. For the sake of system robustness (and simplification) adding another 2 such disks would allow this volume to be configured RAID 5. 

The chassis has sufficient (2.5") disk bays to accomodate.

**Comment by astrodb** [comment]
Can this be closed?

**Comment by GregBlow** [comment]
It can.
