### ISSUE TITLE
Wiki page for object storage

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/somerville-operations#98]
Write a user doc wiki page documenting how to use the object storage.

**Comment by gpfrancis** [comment]
@markgbeckett @astrodb 

I've created a wiki page at https://github.com/lsst-uk/somerville-operations/wiki/Object-Store

I've referenced the RAL documentation as an introduction to Object Storage in general and Swift since it seems pretty copmrehensive and I didn't see much need to recreate it. I've added notes on what I found to be the main issues getting S3 working and a link to the Ceph documentation in case people need more detail.

Let me know if you think anything else is needed.

**Comment by markgbeckett** [comment]
@gpfrancis This looks good to me.  Thanks for writing up. I'm happy for ticket to be closed.
